name: "Deno script"
description: "执行 Deno 代码"
inputs:
  script:
    description: Deno 代码
    required: true
  scriptArgs:
    description: 传递给脚本的参数
    required: false
  args:
    description: 传递给 deno run 的参数
    default: ""
    required: false
outputs:
  return:
    description: 脚本的返回值
    value: ${{steps.run_script.outputs.return}}
runs:
  using: "composite"
  steps:
    - name: Create file
      shell: bash
      run: deno run -A --no-lock "$GITHUB_ACTION_PATH/setup.ts"
      env:
        SCRIPT: ${{inputs.script}}
    - name: Deno run
      shell: bash
      id: run_script
      run: |
        echo ::group:: Cache Dependency
        deno run ${{inputs.args}} "$GITHUB_ACTION_PATH/main.ts" ${{inputs.scriptArgs}}
