name: "Check tags"
description: "检测仓库标签是否存在"
inputs:
  file:
    description: 版本文件路径
    required: true
  field:
    description: 版本字段
    required: false
    default: "version"
  prefix:
    description: 版本标签前缀
    required: false
    default: "v",
  preset:
    required: false
    description: 使用预设
outputs:
  tags:
    description: 不存在的标签列表，格式为一个字符串数组的JSON文本
    value: ${{steps.run_script.outputs.return}}
runs:
  using: "node20"
  main: dist/main.mjs
